Subset linking
mapbox/pt2itp pull request #562
Opened 2020-09-17 18:25 UTC by mapbox-danny

Add the ability to link based on a subset of tokens
 - all address tokens exist in the network string
 - all network tokens exist in the address string

2020-09-22 17:59 UTC, bookest commented on native/src/util/linker.rs
> +                }
Is this short circuit still necessary? It looks like it exists to short circuit to the next potential match, but it's been moved to the end of the loop, so the `continue` doesn't do anything here.

2020-09-22 18:00 UTC, bookest commented on native/src/util/linker.rs
> +
It looks like the implementation doesn't care about order, in which case this check can be performed more simply using `std::collections::HashSet`s and `is_subset`. Though I'm unsure if the order independent comparison is the intent or if we mean to be testing that the address tokens are a subsequence of the network tokens (and vice versa).

2020-09-23 14:00 UTC, mattciferri requested changes

2020-09-23 14:00 UTC, mattciferri commented on native/src/util/linker.rs
> +                        if (ntok_index.is_none()) {
Can this be made a match statement to avoid the unwrap?

2020-09-23 14:00 UTC, mattciferri commented on native/src/util/linker.rs
> +                let tokenlesslev = distance(&tokenless, &potential_tokenless) as f64;
Are these used?

2020-09-23 14:00 UTC, mattciferri commented on native/src/util/linker.rs
> +                    && potential_tokenless.len() >= 1)
Is there a reason tokenless >=1 is required?

2020-09-23 20:02 UTC, bookest approved these changes
A couple of places where we can short circuit to avoid doing some work once we know we either are (or are not) a submatch, but otherwise LGTM.

2020-09-23 20:02 UTC, bookest commented on native/src/types/name.rs
> +        let mut display = display.to_string().replace(r#"""#, ""); // commas are not allowed as they are used to delimit synonyms on output
Should this comment be removed since we're no longer stripping out commas here?

2020-09-24 13:29 UTC, merged

2020-09-24 13:45 UTC, mattciferri commented on native/src/types/name.rs
> +        let mut display = display.to_string().replace(r#"""#, ""); // commas are not allowed as they are used to delimit synonyms on output
@ilissablech Why are we no longer removing commas?

2020-09-24 13:59 UTC, ilissablech commented on native/src/types/name.rs
> +        let mut display = display.to_string().replace(r#"""#, ""); // commas are not allowed as they are used to delimit synonyms on output
@mattciferri items like `Rue Du Dix Neuf Mars 1962,D 149.10` were becoming `Rue Du Dix Neuf Mars 1962D 149.10` & we have a spot to remove commas later in the code that does not interfere with this type of situation https://github.com/mapbox/pt2itp/blob/master/native/src/text/tokens.rs#L130